---
title: The big Minecraft piano
hero_image: images/banner.png
description: Make a piano in Minecraft that plays notes when you step on it.
original_url: https://raspberrypi.org/learning/the-big-minecraft-piano
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: games, music
technologies: raspberry-pi, python, sonic-pi
site_areas: projects
hardware: raspberry-pi
software: python, sonic-pi
version: 3.1.0
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: The big minecraft piano
- title: Receiving messages in Sonic Pi
- title: Sending messages to Sonic Pi
- title: Building piano keys
- title: Planning the keyboard
- title: Clearing some space
- title: Building black keys
- title: Building white keys
- title: Investigating `for` loops
- title: Making an octave
- title: Making the octave again
  completion: internal
- title: Playing your piano
- title: What next?
